### ISSUE TITLE
SMS  client.getSmsClient().submitMessage(  how to remove [TTC]

### ISSUE THREAD

**Issue by jfei** [Nexmo/nexmo-java#112]
SmsSubmissionResult[] responses = client.getSmsClient().submitMessage(new TextMessage(
					fromNumber,
			        toNumber,
			        msg,true));

how to remove [TTC] in sms message ?
thanks

**Comment by jfei** [comment]
wait on line

**Comment by judy2k** [comment]
Hi @jfei - I'm sorry I only just saw this issue - did you find a solution?

**Comment by PurpleStarCB** [comment]
@judy2k how to remove [TTC] in sms message ?

**Comment by judy2k** [comment]
@jfei @PurpleStarCB Hi. This isn't an issue with the nexmo-java library, it's a feature of the Nexmo service. [TTC] is the signature added by tata-direct for messages we send towards China networks.

To discuss having this removed from your SMS messages, please contact our [support team](https://help.nexmo.com/hc/en-us)
