### ISSUE TITLE
How to use voice api?

### ISSUE THREAD

**Issue by 0312birdzhang** [Nexmo/nexmo-java#12]
I found nothing about  <a href="https://docs.nexmo.com/voice/call?utm_source=DEV_REL&utm_medium=github&utm_campaign=python-client-library">voice call api</a>
So...is it no finished yet?

**Comment by leggetter** [comment]
The API is complete. But this library doesn't presently support voice. More documentation on the support it currently supports can be found here:
https://docs.nexmo.com/messaging/java-sdk

If you wish to use the Voice API then I'd suggest either adding the functionality to this library (a PR would be appreciated) or interacting with the API directly with your own code. The API reference can be found here:
https://docs.nexmo.com/voice/call/request
