### ISSUE TITLE
com.nexmo-client,maven config is not working.

### ISSUE THREAD

**Issue by JasonCocomo** [Nexmo/nexmo-java#131]
I configured it in maven like this:

```
<dependency>
      <groupId>com.nexmo</groupId>
      <artifactId>client</artifactId>
      <version>3.1.0</version>
</dependency>
```

but, it is not working.

**Comment by judy2k** [comment]
Hi @JasonCocomo - you haven't given me much to work with!

I've just tested this on my own machine, with the following (complete) Maven file, and it works.

```xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>Maven Quick Start Archetype</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>com.nexmo</groupId>
      <artifactId>client</artifactId>
      <version>3.1.0</version>
    </dependency>
  </dependencies>
</project>
```

If this doesn't work for you, please could you comment, with a complete `pom.xml` to reproduce the problem, and the version number printed when you run `mvn --version`

**Comment by JasonCocomo** [comment]
Thanks a lot, @judy2k for replying.

It was odd. I tried a whole day yesterday but i didn't work, but now it works fine. May be it just a network problem or else.

PS:  Apache Maven 3.3.9

**Comment by judy2k** [comment]
OK. Thanks for letting me know @JasonCocomo. Closing.
