### ISSUE TITLE
Unify exceptions handling 

### ISSUE THREAD

**Issue by peterjurkovic** [Nexmo/nexmo-java#135]
Hi there, would be good to have exception handling consistent.

The current implementation e.g. for verify looks like this
```
 public VerifyResult verify(..) throws IOException, NexmoClientException
``` 
I would suggest create one e.g. `NexmoException` 

```
                                      NexmoException
                                           |
                     +---------------------+-------------------+
                     |                                         |
             NexmoClientException                     NexmoServerException
                     |
    +----------------+----------------+
    |                                 |
BadCredentialsException         XXXXXXXXXXXXX
```

`NexmoClientException` - is a client error (bad credentials, not enough credit , ...)
`NexmoServerException` - is a server error (verify down? or so - is possible to recover if such an error occur - maybe re-try would be successful )

And don't force clients of this library handle also IOException, Would be better rather wrap this exception. 

Also I found one inconsistency (or maybe a bug?) If a user provides bad credentials is being thrown `NexmoResponseParseException` This is runtime exception which might not get handled by a client because is not `instanceof NexmoClientException`.  I had to debug my application to actually find out whats wrong.

I would suggest to change it as following, But it would be a braking change. It would probable require incense major version. 
```
 public VerifyResult verify(..) throws NexmoException
```

**Comment by judy2k** [comment]
I'm aware of the need to unify the exception handling, but it was one of those things that only really emerged while we were doing development.

The NexmoResponseParseException *shouldn't* happen in production, which is why it's a RuntimeException - the client lib should successfully parse all responses. The fact that it does is a bug (and there are probably a few of these). I plan to identify all of these and handle them as part of a project to build a cross-library test-suite.

**Comment by cr0wst** [comment]
Exceptions are being revamped in Version 5. Some of the exceptions are getting renamed. You can see the changes in #255 in which IOException is now being replaced with a `NexmoResponseParseException` as most of the time an `IOException` comes from not being able to deserialize the response (or parse).

Additionally, `NexmoClientException` has been converted to a runtime exception.
