### ISSUE TITLE
INTERNATL_ERR in China and Taiwan

### ISSUE THREAD

**Issue by sheikhrashid** [Nexmo/nexmo-java#138]
Hi,

We are in a big trouble. We are using **Verify API** and facing issues in **China** and **Taiwan**. We are landing on **OnError callback** with **Error (INTERNATL_ERR)**, when we Send the code. 

The strange thing is that, when we type the same number sitting in Pakistan, all works well. But the same numbers are causing problem in other countries.

Can you please let us know, what are the reasons this error is shown? 

China Number: 18938931728
Taiwan Number: 939980360
API Key: 7ff6f3c6

Waiting for your response.

Thanks,
Rashid

**Comment by leggetter** [comment]
Hi @sheikhrashid. This is something that should be handled by the support team. Please provide this info to support@nexmo.com.

**Comment by sheikhrashid** [comment]
Okay
