### ISSUE TITLE
Feature Request: IPv6 support for VerifyClient.check

### ISSUE THREAD

**Issue by newuni** [Nexmo/nexmo-java#145]
Situation

Calling VerifyClient.check method passing an IPV6 for parameter ipAddress generates an error: Invalid value for param: ip_address when using IPv6 format

Request

Support IPv6 address

**Comment by cr0wst** [comment]
Hi @newuni 

This is coming from a lack of support on our API and isn't something we can change in the client library at this time.  I will pass this along to our engineering team.
