### ISSUE TITLE
call HttpClientBuilder.useSystemProperties() before build() to use JVM configuration

### ISSUE THREAD

**Issue by pblanchardie** [Nexmo/nexmo-java#154]
For simpler proxy configuration (amongst other), it sohuld be nice to call [HttpClientBuilder.useSystemProperties](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html#useSystemProperties()) before build() in HttpWrapper.createHttpClient().

**Comment by berry120** [comment]
PR: https://github.com/Nexmo/nexmo-java/pull/207

**Comment by cr0wst** [comment]
Resolved with #207, released with 3.9.0
