### ISSUE TITLE
Signature supplied did not pass verification

### ISSUE THREAD

**Issue by Bajranghudda** [Nexmo/nexmo-java#163]
I am using Android SDK for 2FA verification, recently (a month ago) it was working fine but suddenly it stopped working for me. 

Actually I am using sdk as a module dependency and I checked the version is 
 versionCode 6
 versionName "4.0.0"

I don't know it's a latest version. 

And whenever I try to veryfiy client -
application.getVerifyClient().getUserStatus(prefix, phoneNumber, new SearchListener() {....
.
.
.
.}
SearchListener's onError method is called and the request & response  is - 

Search Request :: {app_id=d97bbc67-c1fe-4d0f-922a-a60a91d2bae6, device_id=ZY2226CSWQ, number=+65 90667128, source_ip_address=55.5.168.192, token=null}

SearchService: SEARCH raw response: Signature: b2fbab0235329f9cf7cbe2d0579f238e. Content: {
                                                                                                  "result_code": 14,
                                                                                                  "result_message": "invalid signature -- the signature supplied did not pass verification",
                                                                                                  "timestamp": "1526360310"
                                                                                              }

Please suggest what went wrong... Why app stopped working ?

**Note** - It's working fine in IOS with same nexmo_app id but stopped working in android.

**Comment by archanapareta** [comment]
I am also in same boat still no solution.

**Comment by cr0wst** [comment]
Hello!

Please use https://github.com/Nexmo/verify-android-sdk/issues/22 for tracking the outcome of this issue as it is related to our Android SDK and not our Java library.

Thanks!
