### ISSUE TITLE
CallInfo should have reason property

### ISSUE THREAD

**Issue by mapuo** [Nexmo/nexmo-java#165]
The `event_url` receives `CallInfo` class but the Voice API can return an error and that error is in the `reason` field. To be able to retrieve the error, please add the `reason` property in the `com.nexmo.client.voice.CallInfo` class.

**Comment by cr0wst** [comment]
Hi @mapuo,

I'm not seeing this field in our api specifications.  Is there some sort of error response that you're able to provide us with so we can look into this further?

**Comment by cr0wst** [comment]
Hi @mapuo 
I don't believe we provide any data objects to help with unmarshalling the JSON that gets sent to the `event_url`.  The `CallInfo` object isn't intended for that purpose.

**Comment by mapuo** [comment]
So we don't know what data will come in the `event_url`?

**Comment by cr0wst** [comment]
Hi @mapuo 

You can see the information that gets sent to the supplied `eventUrl` pages:
- Voice API Reference: https://developer.nexmo.com/api/voice#webhook 
- Guide: Handling Call Status: https://developer.nexmo.com/voice/voice-api/guides/handle-call-status

Some of those fields are going to be the same ones found in the `CallInfo` object and you might be able to unmarshall, however I don't believe that is its intended purpose. 

`CallInfo` was built to handle the response from `VoiceClient#getCallDetails` and isn't setup to handle errors that might get sent to your `eventUrl` as you saw in #164.
