### ISSUE TITLE
VerifyClient

### ISSUE THREAD

**Issue by ravin-d** [Nexmo/nexmo-java#177]
How would one go about on using this if the it's a void method? What can I use from this code to allow me to change scenes in my application if the CODE entered is correct?

client.getVerifyClient().check(ongoingVerify.getRequestId(), CODE);

Help would be much appreciates,
Cheers!

**Comment by cr0wst** [comment]
Hi @ravin-d,

I don't believe the `check` method is a `void` method? It should return a `CheckResult` which has also incorrectly been deprecated and will be un-deprecated in this week's release (3a3786b386b6173b4b64793a3c7ca78dfb9fc45a). As for determining if a verification is successful or not, you can use the `status` property of the `CheckResult`.

Something like:
```java
CheckResult result = client.getVerifyClient().check(ongoingVerify.getRequestId(), CODE);
if (result.getStatus() == CheckResult.STATUS_OK) {
    // Verification was successful
} else {
    // Verification unsuccessful
    System.out.println("Unable to verify, status: " + result.getStatus());
}
```

**Comment by ravin-d** [comment]
Ahhh, ok thank you so much!
