### ISSUE TITLE
Message product's spelling is wrong for Redact API 

### ISSUE THREAD

**Issue by sharif-malik** [Nexmo/nexmo-java#237]
After talking to support team, I got to know that  **message** should **messages** in the RedactRequest.Product enum.

**Comment by sharif-malik** [comment]
https://github.com/Nexmo/nexmo-java/blob/master/src/main/java/com/nexmo/client/redact/RedactRequest.java#L90

**Comment by sharif-malik** [comment]
Here is the documentation from NEXMO(https://developer.nexmo.com/api/redact), which is expecting **messages**

**Comment by sharif-malik** [comment]
#238 Here is the PR to fix this issue

**Comment by sharif-malik** [comment]
@cr0wst Please review this Issue and followed by PR #238

**Comment by sharif-malik** [comment]
Backward compatibility, actually failing my tests when I do integration tests.

**Comment by sharif-malik** [comment]
@cr0wst , it should be `message` instead of `messages`

**Comment by sharif-malik** [comment]
Shall I create another PR for the same. Because currently my tests is picking from text so it always pick `MESSAGE` instead of `MESSAGES`

**Comment by sharif-malik** [comment]
@cr0wst Here is the another PR to fix the value of deprecated product name value

**Comment by sharif-malik** [comment]
Because it fails everytime to pick right product enum

**Comment by cr0wst** [comment]
We only use this object for serialization, it's not intended to be used for deserialization at this time.

**Comment by sharif-malik** [comment]
Yeah, I understand your point. Currently having both enum's value as same is not resilient, I am not able to do integration tests in my project because of deserialisation.

This #240  PR, it will work for all. Isn't it?

**Comment by cr0wst** [comment]
Added explanation in #240.
