### ISSUE TITLE
nexmo does not work  on Android  

### ISSUE THREAD

**Issue by jojupiter** [Nexmo/nexmo-java#256]
the API  << compile 'com.nexmo:client:4.+' >>  does not work on Android Studio gradle 4.4

**Comment by cr0wst** [comment]
Hi @jojupiter 

I'm not sure if you're using Android Studio to develop a non-android application and you're having issues with the dependency system, or if you're specifically trying to use the library in an Android application.

This library is intended to be used in server-side applications as it requires things like API secrets and private keys which shouldn't be stored inside of the application. If you're using Android Studio to develop a server-side application, what error message are you getting?

I wasn't able to duplicate this using the following steps:

Created a new empty Gradle project:
```
gradle init
```

Downgrade the Wrapper to 4.4

```
gradle wrapper --gradle-version 4.4
```
