### ISSUE TITLE
No option for selecting workflow 6 i.e. only SMS from VerifyRequest.Workflow

### ISSUE THREAD

**Issue by anmol5varma** [Nexmo/nexmo-java#275]
https://developer.nexmo.com/verify/guides/workflows-and-events
Workflow 6 is absent from `VerifyRequest.Workflow` Class. How do I implement that using nexmo java sdk?

**Comment by lornajane** [comment]
Thanks for reaching out to us about this, we've just released a new version of the SDK that adds support for these workflows. Please can you try installing version 5.2.1 and let us know how you get on?

**Comment by lornajane** [comment]
Closing, but re-open if anything more is needed here
