### ISSUE TITLE
Should support full JSON structures when generating JWTs

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-java#42]
`JWTAuthMethod` presently offers a `String constructToken(long iat, String jti)` method.

It should be possible to in more complex structures.

See: https://github.com/Nexmo/client-library-specification/issues/22

**Comment by cr0wst** [comment]
This is now handled in https://github.com/nexmo/nexmo-jwt-jdk which will be the default JWT provider for the server SDK. Users wishing to customize and generate JWTs should bring this library in instead.
