### ISSUE TITLE
Missing a proper release version?

### ISSUE THREAD

**Issue by nbleisch** [Nexmo/nexmo-java#47]
Hey there, I (we) would like to use your client but feel a bit uncertain about using your SNAPSHOT version because we would like to make our build artifact as reproducible as possible. 
Therefore, I'd like to ask if it's possible to introduce proper release versions next to the snapshots.

Thanks in advance

**Comment by judy2k** [comment]
Hi there!

The SNAPSHOT status accurately reflects the current stability of the library's interface. *However* I've nearly finished the changes required for a final release. If you're using the Voice API then this snapshot will be compatible with the release. The other APIs are all being restructured first. You may be best waiting a couple of days for the non SNAPSHOT release.

**Comment by nbleisch** [comment]
Thx for your quick reply @judy2k .
For now, we're only interested in sending SMS messages.
Looking forward for your "non-SNAPSHOT" release.

**Comment by judy2k** [comment]
Hi @nbleisch - we've just released 2.0.0 final onto Maven Central, and we'd love to know what you think!

**Comment by nbleisch** [comment]
Works very well. Thanks
