### ISSUE TITLE
`AbstractMethod` is in the wrong package.

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-java#61]
`AbstractMethod` is in `com.nexmo.client.voice.endpoints`, but is shared across all the APIs, so should be under `com.nexmo.client` or a common package.

**Comment by ferozbaig96** [comment]
Can I work on this issue?

**Comment by cr0wst** [comment]
Hi @arpitpandey0209, feel free to submit a PR for this issue. I would recommend starting with the `version-4` branch as this will most likely be a backwards incompatible change and would need to be released as part of the next major version.

**Comment by Soundug** [comment]
Hi @cr0wst I would like to work on this issue. Is it up for grabs?

**Comment by cr0wst** [comment]
Resolved in #225
