### ISSUE TITLE
using setEventUrl for Voice Call returns an invalid parameter Bad Request

### ISSUE THREAD

**Issue by waggyza** [Nexmo/nexmo-java#63]
When calling setEventUrl on a Call object, and then calling the VoiceClient createCall function using this object, the returned CallEvent has no set objects and no call is made. Output shows:

Received: {"type":400,"title":"Bad Request","invalid_parameters":[{"reason":"Invalid type parameter provided","name":"event_url"}]}

If setEventUrl is not called, then the CallEvent is correctly set and a call is made.

**Comment by judy2k** [comment]
@waggyza Thanks for reporting this. I'll investigate and get back to you.

**Comment by ChrisGuzman** [comment]
Hi @waggyza 

I think this is a bug in the library. When setting an event url, the library should convert that string to a list before it sends it to the API. I'll have a PR filed for this soon.

Thanks for filing this bug! We'd like to send you a thank you gift. Can you email me at chris.guzman [at] nexmo [dot] com?
