### ISSUE TITLE
Allow injecting HttpClient for NexmoClient

### ISSUE THREAD

**Issue by Saheb** [Nexmo/nexmo-java#7]
HttpClient is strongly coupled in Nexmo's clients, and there isn't a a setter which allows to configure and plugin a HttpClient of my choice. My use case being I want to plugin a proxy for httpClient.

I am in urgent need for this functionality, so kindly let me know if any existing contributors is going to work on this or you would require me to fix it and send a PR.

**Comment by thepeachbeetle** [comment]
Hi,

There is no effort under way currently to do this, so please go ahead and submit a PR

**Comment by Saheb** [comment]
https://github.com/Nexmo/nexmo-java/pull/8
