### ISSUE TITLE
Bump httpclient to 4.2 (or superior) to pre-configure a client using Java SE networking properties

### ISSUE THREAD

**Issue by emcrisostomo** [Nexmo/nexmo-java#9]
`HttpClient` v. 4.2 [introduces](https://issues.apache.org/jira/browse/HTTPCLIENT-1128) the possibility of pre-configuring a client using the standard [Java SE networking properties](http://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html).  I suggest bumping the dependency to at least 4.2 and refactor the code to take advantage of this possibility.  It should be as simple as creating `HttpClient` instances like this and configure them:

```
HttpClientBuilder.create().useSystemProperties().build();
```

Currently, the only workaround is passing the `NexmoSmsClient` instance a configured `HttpClient` instance:

```
NexmoSmsClient nsc = new NexmoSmsClient(key, secret);
nsc.setHttpClient(HttpClientBuilder.create().useSystemProperties().build());
```

However, it seems natural to me expecting that a library like this would take into account the aforementioned networking properties transparently.

**Comment by judy2k** [comment]
HttpClient has been bumped to 4.5 in the first `2.0.0-SNAPSHOT` release.
