### ISSUE TITLE
Implement `linkNumber`

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-java#97]

**Comment by mheap** [comment]
Looks like you can do this using `Number::update`. We may want to add a better API in the future e.g. `$number->linkToApplication($app)` but this works for now. I'll add examples once I get to NDP

**Comment by judy2k** [comment]
@mheap I think you closed this issue on nexmo-java instead of nexmo-php by mistake :)

**Comment by mheap** [comment]
Whoops! Looks like I did
